### ISSUE TITLE
Is `crypto_signcrypt_tbsr_verify_public` spelled correctly?

### ISSUE THREAD

**Issue by michelp** [jedisct1/libsodium-signcryption#3]
It seems like the name should be `crypto_signcrypt_tbsbr_verify_public`, but it's like that in the header, implementation and test, so maybe there's another acronym I'm missing?

https://github.com/jedisct1/libsodium-signcryption/blob/master/src/tbsbr/signcrypt_tbsbr.h#L52

**Comment by jedisct1** [comment]
Good catch!

That was indeed a typo. Fixed in 7d42021, thank you!

**Comment by michelp** [comment]
Your welcome!  FYI I've included `libsodium-signcryption` and `libsodium-xchacha20-siv` in the next release of pgsodium by copying the code and reproducing your license.  Do you have any plans to include them in libsodium?
